package gui;

import javax.swing.*;
import databaserunner.*;

public class StartPage extends javax.swing.JFrame {

    //our fields
    private String elementsFile;
    private String binaryCompoundsFile;
    private String reactionsFile;
    
    private int firstValence;
    private int increment;
    
    private DatabaseGUI databaseGUI;
    
    /**
     * Creates new form Start
     */
    public StartPage(DatabaseGUI databaseGUI) {
        this.databaseGUI = databaseGUI;
        this.firstValence = PeriodicTable.DEFAULT_FIRST_VALENCE;
        this.increment = PeriodicTable.DEFAULT_INCREMENT;
        this.initComponents();
        this.jTextFieldElementsFileName.setText(DatabaseGUI.DEFAULT_ELEMENTS_FILE);
        this.jTextFieldBinaryCompoundsFileName.setText(DatabaseGUI.DEFAULT_BINARY_COMPOUNDS_FILE);
        this.jTextFieldReactionsFileName.setText(DatabaseGUI.DEFAULT_REACTIONS_FILE);
    }

    //our methods
    public void start(StartPage startPage) {
        this.initConstants();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                startPage.setVisible(true);
            }
        });
    }
    
    private void initConstants() {
        this.jLabelElementsFileName.setText(DatabaseGUI.ELEMENTS_FILE_NAME);
        this.jLabelBinaryCompoundsFileName.setText(DatabaseGUI.BINARY_COMPOUNDS_FILE_NAME);
        this.jLabelReactionsFileName.setText(DatabaseGUI.REACTIONS_FILE_NAME);
        this.jLabelFileExtension1.setText(DatabaseGUI.FILE_EXTENSION);
        this.jLabelFileExtension2.setText(DatabaseGUI.FILE_EXTENSION);
        this.jLabelFileExtension3.setText(DatabaseGUI.FILE_EXTENSION);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel("TITLE", SwingConstants.CENTER);
        jTextFieldElementsFileName = new javax.swing.JTextField();
        jComboBoxFirstValence = new javax.swing.JComboBox<>();
        jComboBoxIncrement = new javax.swing.JComboBox<>();
        jLabelIncrement = new javax.swing.JLabel();
        jLabelFileExtension1 = new javax.swing.JLabel();
        jLabelElementsFileName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelBinaryCompoundsFileName = new javax.swing.JLabel();
        jTextFieldBinaryCompoundsFileName = new javax.swing.JTextField();
        jLabelReactionsFileName = new javax.swing.JLabel();
        jTextFieldReactionsFileName = new javax.swing.JTextField();
        jLabelInfo1 = new javax.swing.JLabel();
        jLabelFirstValence1 = new javax.swing.JLabel();
        jLabelFileExtension3 = new javax.swing.JLabel();
        jLabelFileExtension2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setText("Welcome to The Chemical Database!");

        jTextFieldElementsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldElementsFileName.setText("elements");

        jComboBoxFirstValence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxFirstValence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBoxFirstValence.setSelectedItem(String.valueOf(firstValence));
        jComboBoxFirstValence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFirstValenceActionPerformed(evt);
            }
        });

        jComboBoxIncrement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxIncrement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBoxIncrement.setSelectedItem(String.valueOf(increment));
        jComboBoxIncrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIncrementActionPerformed(evt);
            }
        });

        jLabelIncrement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIncrement.setText("Increment");

        jLabelFileExtension1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFileExtension1.setText(".txt");

        jLabelElementsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelElementsFileName.setText("Elements File Name");

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("A minimal level of chemistry knowledge is required to use this program effectively. Note that the program is not meant to simulate reality.\nUnusual interactions can and will happen depending on the provided data.\n\nStarting the Database\n- Enter file names. If you are creating a new database, create 3 new .txt files in the directory of TheGlateChemicalDatabase.jar, \nrepresenting elements, compounds, and reactions. Make sure to leave the text files themselves blank!\n- If the files are ever tampered with the program will not run and an error message will be displayed.\n- First valence represents the amount of elements in the first row of the periodic table.\n- Increment determines the scaling of the number of elements in each consecutive row.\n- These 2 variables will determine how the periodic table looks and the nature of the elements during a reaction.\n\nReloading/Saving\n- The save button will save all the contents of your database to the 3 files specified on the start page.\n- The reload button allows you to reload your files and change the first valence and increment if need be (doing so will affect all elements,\ncompounds, and reactions!)\n- A prompt to save will appear when attempting to close or reload the program after making changes.\n\nAdding Elements\n- All element parameters must fall within the field restrictions outlined below. Otherwise, an error message will be displayed.\n- Make sure to click submit or the element will not be added.\n\nRemoving Chemicals\n- Enter a chemical name in the text field and click remove chemical.\n- If the chemical name is present in the database, the chemical will be removed. Otherwise, an error message will be shown.\n\nSorting Chemicals\n- Select a property in the drop down menu and click sort to list the chemicals by the property selected.\n- Click on a listed chemical to have its properties displayed on the right.\n\nEditing Chemicals\n- Search for a chemical by name using the search field.\n- All chemical parameters must fall within the field restrictions outlined below. Otherwise, an error message will be displayed.\n- Make sure to click submit or your changes will not be saved.\n\nListing Compounds\n- Compounds are listed in order of creation.\n- Clicking on a compound name displays the compound and its properties on the right.\n\nListing Reactions\n- Reactions consisting of reactants and products are listed in order of creation.\n- Remove selected reaction removes the selected reaction.\n\nSimulating Reactions\n- Enter element names in their allotted fields and click submit to react them. Note that only element names may be submitted as \nreactants.\n- If the elements are valid and the reaction does not already exist, the reaction will occur. Otherwise, an error message will be displayed.\n- Enter the name of the product and submit. The other properties are optional. Leaving the screen without entering the name will forfeit \nthe data of that reaction\n- The try again button allows you to simulate another reaction.\n\nField Restrictions\n- Common Name (max length 32 characters; no repeats)\n- Atomic Symbol (max length 3 characters; no repeats)\n- 0 < Atomic Number < 1000000 (no repeats)\n- Neutrons >= 0\n- Molar Mass >= 0\n- Density >= 0\n- Ionization Energy >= 0\n- 0 <= Electronegativity <= 4\n- Colour (max length 32 characters)");
        jTextArea1.setMinimumSize(new java.awt.Dimension(120, 21));
        jScrollPane1.setViewportView(jTextArea1);

        jLabelBinaryCompoundsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBinaryCompoundsFileName.setText("Compounds File Name");

        jTextFieldBinaryCompoundsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBinaryCompoundsFileName.setText("compounds");

        jLabelReactionsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReactionsFileName.setText("Reactions File Name");

        jTextFieldReactionsFileName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldReactionsFileName.setText("reactions");

        jLabelInfo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo1.setText("* = required field");

        jLabelFirstValence1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFirstValence1.setText("First Valence");

        jLabelFileExtension3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFileExtension3.setText(".txt");

        jLabelFileExtension2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFileExtension2.setText(".txt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSubmit)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelInfo1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelElementsFileName)
                                            .addComponent(jLabelReactionsFileName)
                                            .addComponent(jLabelBinaryCompoundsFileName)
                                            .addComponent(jTextFieldBinaryCompoundsFileName)
                                            .addComponent(jTextFieldElementsFileName)
                                            .addComponent(jTextFieldReactionsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelFileExtension1)
                                                .addGap(102, 102, 102)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxFirstValence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelFirstValence1))
                                                .addGap(86, 86, 86)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelIncrement)))
                                            .addComponent(jLabelFileExtension3)
                                            .addComponent(jLabelFileExtension2)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIncrement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelElementsFileName)
                            .addComponent(jLabelFirstValence1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldElementsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFileExtension1)
                            .addComponent(jComboBoxFirstValence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBinaryCompoundsFileName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBinaryCompoundsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFileExtension2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelReactionsFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldReactionsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFileExtension3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jLabelInfo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SUBMIT button
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        this.elementsFile = this.jTextFieldElementsFileName.getText();
        this.binaryCompoundsFile = this.jTextFieldBinaryCompoundsFileName.getText();
        this.reactionsFile = this.jTextFieldReactionsFileName.getText();
        this.firstValence = Integer.parseInt((String)(this.jComboBoxFirstValence.getSelectedItem()));
        this.increment = Integer.parseInt((String)(this.jComboBoxIncrement.getSelectedItem()));
        
        char elementsFileCheck = this.databaseGUI.validateFile(elementsFile);
        char binaryCompoundsFileCheck = this.databaseGUI.validateFile(binaryCompoundsFile);
        char reactionsFileCheck = this.databaseGUI.validateFile(reactionsFile);
        
        if(elementsFileCheck == DatabaseGUI.VALID_FILE && binaryCompoundsFileCheck == DatabaseGUI.VALID_FILE && reactionsFileCheck == DatabaseGUI.VALID_FILE) {
            this.elementsFile = this.elementsFile + DatabaseGUI.FILE_EXTENSION;
            this.binaryCompoundsFile = this.binaryCompoundsFile + DatabaseGUI.FILE_EXTENSION;
            this.reactionsFile = this.reactionsFile + DatabaseGUI.FILE_EXTENSION;
            
            this.databaseGUI.constructDatabase(this.elementsFile, this.binaryCompoundsFile, this.reactionsFile, this.firstValence, this.increment);       
            this.databaseGUI.startHomePage();
            this.setVisible(false);
        } else {
            String errorMessage = DatabaseGUI.ERROR;
            
            if(elementsFileCheck == DatabaseGUI.EMPTY_FILE)
                errorMessage += DatabaseGUI.ELEMENTS_FILE_NAME + DatabaseGUI.ERROR_FIELD_EMPTY + DatabaseGUI.LINE_BREAK;
            else if(elementsFileCheck == DatabaseGUI.FILE_NAME_TOO_LONG)
                errorMessage += DatabaseGUI.ELEMENTS_FILE_NAME + DatabaseGUI.ERROR_TOO_LONG + DatabaseGUI.LINE_BREAK;
            else if (elementsFileCheck != DatabaseGUI.VALID_FILE) 
                errorMessage += DatabaseGUI.ELEMENTS_FILE_NAME + DatabaseGUI.ERROR_FILE_INVALID + DatabaseGUI.LINE_BREAK + DatabaseGUI.CHAR_QUOTE + String.valueOf(elementsFileCheck) + DatabaseGUI.CHAR_QUOTE;

            if(binaryCompoundsFileCheck == DatabaseGUI.EMPTY_FILE)
                errorMessage += DatabaseGUI.BINARY_COMPOUNDS_FILE_NAME + DatabaseGUI.ERROR_FIELD_EMPTY + DatabaseGUI.LINE_BREAK;
            else if(binaryCompoundsFileCheck == DatabaseGUI.FILE_NAME_TOO_LONG)
                errorMessage += DatabaseGUI.BINARY_COMPOUNDS_FILE_NAME + DatabaseGUI.ERROR_TOO_LONG + DatabaseGUI.LINE_BREAK;
            else if (binaryCompoundsFileCheck != DatabaseGUI.VALID_FILE)
                errorMessage += DatabaseGUI.BINARY_COMPOUNDS_FILE_NAME + DatabaseGUI.ERROR_FILE_INVALID + DatabaseGUI.LINE_BREAK + DatabaseGUI.CHAR_QUOTE + String.valueOf(binaryCompoundsFileCheck) + DatabaseGUI.CHAR_QUOTE;
            
            if(reactionsFileCheck == DatabaseGUI.EMPTY_FILE)
                errorMessage += DatabaseGUI.REACTIONS_FILE_NAME + DatabaseGUI.ERROR_FIELD_EMPTY + DatabaseGUI.LINE_BREAK;
            else if(reactionsFileCheck == DatabaseGUI.FILE_NAME_TOO_LONG) 
                errorMessage += DatabaseGUI.REACTIONS_FILE_NAME + DatabaseGUI.ERROR_TOO_LONG + DatabaseGUI.LINE_BREAK;
            else if (reactionsFileCheck != DatabaseGUI.VALID_FILE)
                errorMessage += DatabaseGUI.REACTIONS_FILE_NAME + DatabaseGUI.ERROR_FILE_INVALID + DatabaseGUI.LINE_BREAK + DatabaseGUI.CHAR_QUOTE + String.valueOf(reactionsFileCheck) + DatabaseGUI.CHAR_QUOTE;  
            
            JOptionPane.showMessageDialog(null, errorMessage);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jComboBoxFirstValenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFirstValenceActionPerformed
        JOptionPane.showMessageDialog(null, DatabaseGUI.WARNING + DatabaseGUI.WARNING_CHANGING_PERIODIC_PROPERTY);
    }//GEN-LAST:event_jComboBoxFirstValenceActionPerformed

    private void jComboBoxIncrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIncrementActionPerformed
        JOptionPane.showMessageDialog(null, DatabaseGUI.WARNING + DatabaseGUI.WARNING_CHANGING_PERIODIC_PROPERTY);
    }//GEN-LAST:event_jComboBoxIncrementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxFirstValence;
    private javax.swing.JComboBox<String> jComboBoxIncrement;
    private javax.swing.JLabel jLabelBinaryCompoundsFileName;
    private javax.swing.JLabel jLabelElementsFileName;
    private javax.swing.JLabel jLabelFileExtension1;
    private javax.swing.JLabel jLabelFileExtension2;
    private javax.swing.JLabel jLabelFileExtension3;
    private javax.swing.JLabel jLabelFirstValence1;
    private javax.swing.JLabel jLabelIncrement;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JLabel jLabelReactionsFileName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldBinaryCompoundsFileName;
    private javax.swing.JTextField jTextFieldElementsFileName;
    private javax.swing.JTextField jTextFieldReactionsFileName;
    // End of variables declaration//GEN-END:variables
}